spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:D:/app/folders/db/sample
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

properties:
  foldersPath: "D:/app/folders"
  phoneNumber: "0638080251"
  photosDir: "C:/Users/Anton/Desktop/foto"